codepen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from codepen import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('', include('home.urls')),
    path('', include('user.urls')),
    path('', include('dashboard.urls')),
    path('', include('pen.urls')),
    path('', include('setting.urls')),
    path('404/', views.url_not_found, name='404'),
    path('search/', views.search, name='search'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'codepen.views.error_404'

pen/urls.py
from django.urls import path
from . import views

app_name = 'pen'
urlpatterns = [
    path('new-pen/', views.new_pen, name='new_pen'),
    path('<slug:username>/pen/<slug:pen_slug>/', views.single_pen, name='single_pen'),
    path('<slug:username>/pen/edit/', views.pen_edit, name="pen_edit"),
    path('<slug:username>/pen/delete/', views.pen_delete, name="pen_delete"),
    path('pen-filter/', views.pen_filter, name="pen_filter"),
    path('tag/<slug:tag_name>/', views.tag, name="tag"),
    path('pen/save/', views.vms_save_pen, name="save_pen"),
    path('pen/live-edit/', views.vms_live_edit, name="live_edit"),
    path('<slug:username>/pen/full/<slug:pen_slug>/', views.single_pen_full, name='single_pen'),
]

user/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'user'
urlpatterns = [
    path('login/', views.user_login, name="login_url"),
    path('signup/', views.signup, name="signup_url"),
    path('logout/', views.user_logout, name="logout_url"),
    path('auth/forgot-password/', views.forgot_password, name="forgot_password"),
    path('auth/change-password', views.change_password, name="change_password"),
    path('auth/change-password-token', views.change_password_token, name="change_password_token"),
    path('auth/change-password-code', views.change_password_code, name="change_password_code"),
    path('auth/change-password-resend-code', views.change_password_resend_code, name="change_password_resend_auth"),
    path('auth/verified-token', views.verified_token, name="auton_token"),
    path('auth/verified-code', views.verified_code, name="auton_code"),
    path('auth/verified-code-resend', views.verified_code_resend, name="verified_code_resend"),
    path('auth/user-validation', views.check_user_validation, name='user_validation')
]

templates/form/change-password.html
{% extends 'main/base/base.html' %}
{% block content %}
    <div id="form-area">
        <div class="form-section">
            <div id="form">
                <form id="change-password" method="post">
                    <div class="form-logo">
                        <svg id="cp-logo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                             x="0px" y="0px"
                             viewBox="0 0 256 48" xml:space="preserve">
                            <polyline class="st0" points="151.2,10.5 133.8,10.5 133.8,37.6 151.2,37.6 "/>
                            <polyline class="st0" points="217,10.5 199.6,10.5 199.6,37.6 217,37.6 "/>
                            <line class="st0" x1="211.2" y1="24" x2="199.6" y2="24"/>
                            <line class="st0" x1="145.4" y1="24" x2="133.8" y2="24"/>
                            <polyline class="st0" points="232.5,37.5 232.5,10.4 253.8,37.5 253.8,10.4 "/>
                            <path class="st0" d="M166.7,25.9h11.6c4.3,0,7.7-3.5,7.7-7.7s-3.5-7.7-7.7-7.7h-11.6v27.1"/>
                            <path class="st0"
                                  d="M26.4,14.3c-2.5-2.5-5.8-3.9-9.7-3.9C9,10.5,3.2,16.3,3.2,24S9,37.5,16.8,37.5c3.9,0,7.2-1.5,9.7-3.9"/>
                            <path class="st0"
                                  d="M120.3,24c0,7.7-5.8,13.5-13.5,13.5H97V10.4h9.7C114.5,10.4,120.3,16.3,120.3,24L120.3,24z"/>
                            <path class="st1"
                                  d="M58.6,1.8L58,2.3c-1.3,1-2,2.6-2,4.3l0,35.3c0,1.7,0.7,3.3,2,4.3c1.8,1.4,4.3,1.4,6-0.1L86,27.9c1.2-1,1.9-2.6,1.9-4.2v-0.1c0-1.7-0.7-3.2-2-4.3L64.6,1.9C62.9,0.4,60.4,0.4,58.6,1.8z M34.2,21.8l13.2-10.2c0.8-0.6,1.8,0,1.8,1v3c0,0.4-0.2,0.7-0.4,0.9l-8.3,6.9v0.1l8.2,6.5c0.3,0.2,0.5,0.6,0.5,1v3.4c0,1-1.1,1.5-1.8,1L34.2,25.2c-0.3-0.2-0.5-0.6-0.5-1v-1.5C33.7,22.4,33.9,22,34.2,21.8z M65.4,11.6l12.4,10.2c0.3,0.2,0.4,0.6,0.4,1v1.5c0,0.4-0.2,0.7-0.4,1L65.4,35.4c-0.7,0.6-1.7,0-1.7-1V31c0-0.4,0.2-0.7,0.4-1l7.8-6.5v-0.1l-7.8-6.9c-0.3-0.2-0.4-0.6-0.4-0.9v-3C63.7,11.6,64.7,11.1,65.4,11.6z"/>
                        </svg>
                    </div>
                    <h4 class="form-title">{{ form_name }}</h4>
                    {% if request.COOKIES.success %}
                        <div class="form-success">
                            <span class="success">{{ request.COOKIES.success }}</span>
                        </div>
                    {% endif %}

                    <div class="form-error">
                        {% if auth_error %}
                            <span class="error">{{ auth_error }}</span>
                        {% endif %}
                    </div>
                    <div>
                        <div class="form-field">
                            <i class="fas fa-lock"></i>
                            <input type="password" name="password" id="password" placeholder="Enter Your Password"
                                   class="password" required>
                        </div>
                        <div class="form-helper">{{ form_helper }}</div>
                        <div class="form-error">
                            {% if password_error %}<span class="error">{{ password_error }}</span>{% endif %}
                        </div>
                    </div>
                    <div>
                        <div class="form-field">
                            <i class="fas fa-lock"></i>
                            <input type="password" name="cpassword" id="cpassword" placeholder="Confirm Password"
                                   class="cpassword" required>
                        </div>
                        <div class="form-error">
                            {% if password_error %}<span class="error">{{ password_error }}</span>{% endif %}
                        </div>
                    </div>
                    <div class="form-submit">
                        <button type="submit">Change Password</button>
                    </div>
                    <div class="form-breaker">
                        <hr class="breaker">
                    </div>
                    <div class="form-footer">
                        <div class="have-account"><span>Don't have and account? </span><a
                                href="{% url 'user:signup_url' %}"> Sign Up </a></div>
                    </div>
                    {% csrf_token %}
                    <input type="hidden" name="login" id="submitted" value="true">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/form/change_password_email_template.html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title> verification email address</title>
</head>
<body>
<table style="background-color:#f2f2f2; color: #586069; max-width: 650px;margin: 0 auto;line-height: 1.25; word-break: break-word; word-wrap: break-word; ">
    <tbody>
    <tr>
        <td>
            <table style="display: flex; align-items: center; justify-content: center; max-width: 550px; margin: 5%; padding: 5%; background-color: #ffffff;text-align: center">
                <tbody>
                <tr>
                    <td align="center" style="margin-bottom: 10px; text-align: center">
                        <a href="//{{ site_url.domain }}" class="site-logo">
                            <img src="https://cdn.jsdelivr.net/gh/developershohel/cdn.codepen.live@main/img/codepen.png"
                                 alt="{{ site_url.name }}">
                        </a>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <h1 style="font-size: 20px;"> Almost done, <strong
                                style="color:#24292e;">{{ username }}</strong> To complete your
                            {{ site_url.name }} sign up, we just need to verify your
                            email address: <strong style="color:#24292e; font-size: 20px;">{{ email }}</strong>
                        </h1>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <a class="pn-activation-link-button btn btn-primary" href="{{ verified_token_url }}"
                           target="_blank"
                           style="box-sizing: border-box; text-decoration: none; background-color: #0366d6; border-radius: 5px; color: #ffffff; display: inline-block; font-size: 14px; font-weight: bold; cursor: pointer; margin: 0; padding: 10px 20px; border: 1px solid #0366d6;">Verify
                            email address</a>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <h4 style="font-size: 16px; color: #586069; margin: 0;">Once verified, you can start using all
                            of {{ site_url.name }} features to explore, build, and share projects.</h4>
                        <p style="font-size: 14px;">Button not working? Paste the following link into your browser:<br/>
                            <a class="activation-link text-primary" href="{{ verified_token_url }}"
                               style="font-size:14px; color: #0366d6;word-break: break-all;"
                               target="_blank">{{ verified_token_url }}</a>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <h1 style="text-align: center; font-size: 20px; font-weight: bolder; color: #24292e;">Confirm by
                            verification code</h1>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <h4 style="font-size: 16px; margin: 0; color: #586069;">Please enter this verification code to
                            verify your email and get started on {{ site_url.name }}:<br/> <strong
                                    style="color: #24292e; font-size: 24px;">{{ verified_code }}</strong></h4>
                        <span style="font-size: 14px;">Verification codes expire after two hours.</span>
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <p style="color: #24292e; font-size: 14px;">You are receiving this email because you recently
                            created a new account on {{ site_url.name }}. If this was not you, please ignore this
                            email.</p>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <hr class="pn-horizontal-line"
                            style="height: 0; overflow: visible; border-top-color: #e1e4e8; color: #959da5; font-size: 12px; line-height: 18px; background-color: #d9d9d9; margin: 10px 0; border-style: solid none none; border-width: 1px 0 0;">
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 12px;">
                        <span>&copy;  {{ year }} <a href="//{{ site_url.domain }}"
                                                    style="text-decoration: none; color: #337ab7; padding-left:5px;"> {{ site_url.name }} </a><a
                                href="/privacy_policy "
                                style="text-decoration: none; color: #337ab7; padding: 0 5px;">Privacy</a>login on <a
                                href=" {% url 'user:login_url' %} "
                                style="text-decoration: none; color: #337ab7; padding-left: 5px;">{{ site_url.name }}</a></span>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
</body>
</html>

templates/form/forgot-password.html
{% extends 'main/base/base.html' %}
{% block content %}
    <div id="form-area">
        <div class="form-section">
            <div id="form">
                <form id="forgot-password" method="post">
                    <div class="form-logo">
                        <svg id="cp-logo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                             x="0px" y="0px"
                             viewBox="0 0 256 48" xml:space="preserve">
                            <polyline class="st0" points="151.2,10.5 133.8,10.5 133.8,37.6 151.2,37.6 "/>
                            <polyline class="st0" points="217,10.5 199.6,10.5 199.6,37.6 217,37.6 "/>
                            <line class="st0" x1="211.2" y1="24" x2="199.6" y2="24"/>
                            <line class="st0" x1="145.4" y1="24" x2="133.8" y2="24"/>
                            <polyline class="st0" points="232.5,37.5 232.5,10.4 253.8,37.5 253.8,10.4 "/>
                            <path class="st0" d="M166.7,25.9h11.6c4.3,0,7.7-3.5,7.7-7.7s-3.5-7.7-7.7-7.7h-11.6v27.1"/>
                            <path class="st0"
                                  d="M26.4,14.3c-2.5-2.5-5.8-3.9-9.7-3.9C9,10.5,3.2,16.3,3.2,24S9,37.5,16.8,37.5c3.9,0,7.2-1.5,9.7-3.9"/>
                            <path class="st0"
                                  d="M120.3,24c0,7.7-5.8,13.5-13.5,13.5H97V10.4h9.7C114.5,10.4,120.3,16.3,120.3,24L120.3,24z"/>
                            <path class="st1"
                                  d="M58.6,1.8L58,2.3c-1.3,1-2,2.6-2,4.3l0,35.3c0,1.7,0.7,3.3,2,4.3c1.8,1.4,4.3,1.4,6-0.1L86,27.9c1.2-1,1.9-2.6,1.9-4.2v-0.1c0-1.7-0.7-3.2-2-4.3L64.6,1.9C62.9,0.4,60.4,0.4,58.6,1.8z M34.2,21.8l13.2-10.2c0.8-0.6,1.8,0,1.8,1v3c0,0.4-0.2,0.7-0.4,0.9l-8.3,6.9v0.1l8.2,6.5c0.3,0.2,0.5,0.6,0.5,1v3.4c0,1-1.1,1.5-1.8,1L34.2,25.2c-0.3-0.2-0.5-0.6-0.5-1v-1.5C33.7,22.4,33.9,22,34.2,21.8z M65.4,11.6l12.4,10.2c0.3,0.2,0.4,0.6,0.4,1v1.5c0,0.4-0.2,0.7-0.4,1L65.4,35.4c-0.7,0.6-1.7,0-1.7-1V31c0-0.4,0.2-0.7,0.4-1l7.8-6.5v-0.1l-7.8-6.9c-0.3-0.2-0.4-0.6-0.4-0.9v-3C63.7,11.6,64.7,11.1,65.4,11.6z"/>
                        </svg>
                    </div>
                <h4 class="form-title">{{ form_name }}</h4>
                    {% if request.COOKIES.success %}
                        <div class="form-success">
                            <span class="success">{{ request.COOKIES.success }}</span>
                        </div>
                    {% endif %}

                    <div class="form-error">
                        {% if auth_error %}
                            <span class="error">{{ auth_error }}</span>
                        {% endif %}
                    </div>
                    <div>
                        <div class="form-field">
                            <i class="fas fa-envelope"></i>
                            <input type="text" name="username" id="username" placeholder="Enter Your Username" class="username" value="{% if username %}{{ username }}{% endif %}" required>
                        </div>
                        <div class="form-error">
                            {% if username_error %}<span class="error">{{ username_error }}</span>{% endif %}
                        </div>
                    </div>
                    <div class="form-submit">
                        <button type="submit">Continue</button>
                    </div>
                    <div class="form-breaker">
                        <hr class="breaker">
                    </div>
                    <div class="form-footer">
                        <div class="have-account"><span>Don't have and account? </span><a
                                href="{% url 'user:signup_url' %}"> Sign Up </a></div>
                    </div>
                    {% csrf_token %}
                    <input type="hidden" name="login" id="submitted" value="true">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/form/login_email_template.html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title> verification email address</title>
</head>
<body>
<table style="background-color:#f2f2f2; color: #586069; max-width: 650px;margin: 0 auto;line-height: 1.25; word-break: break-word; word-wrap: break-word; ">
    <tbody>
    <tr>
        <td>
            <table style="display: flex; align-items: center; justify-content: center; max-width: 550px; margin: 5%; padding: 5%; background-color: #ffffff;text-align: center">
                <tbody>
                <tr>
                    <td align="center" style="margin-bottom: 10px; text-align: center">
                        <a href="//{{ site_url.domain }}" class="site-logo">
                            <img src="https://cdn.jsdelivr.net/gh/developershohel/cdn.codepen.live@main/img/codepen.png"
                                 alt="{{ site_url.name }}">
                        </a>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <h1 style="font-size: 20px;"> Almost done, <strong
                                style="color:#24292e;">{{ username }}</strong> To complete your
                            {{ site_url.name }} sign up, we just need to verify your
                            email address: <strong style="color:#24292e; font-size: 20px;">{{ email }}</strong>
                        </h1>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <a class="pn-activation-link-button btn btn-primary" href="{{ verified_token_url }}"
                           target="_blank"
                           style="box-sizing: border-box; text-decoration: none; background-color: #0366d6; border-radius: 5px; color: #ffffff; display: inline-block; font-size: 14px; font-weight: bold; cursor: pointer; margin: 0; padding: 10px 20px; border: 1px solid #0366d6;">Verify
                            email address</a>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <h4 style="font-size: 16px; color: #586069; margin: 0;">Once verified, you can start using all
                            of {{ site_url.name }} features to explore, build, and share projects.</h4>
                        <p style="font-size: 14px;">Button not working? Paste the following link into your browser:<br/>
                            <a class="activation-link text-primary" href="{{ verified_token_url }}"
                               style="font-size:14px; color: #0366d6;word-break: break-all;"
                               target="_blank">{{ verified_token_url }}</a>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <h1 style="text-align: center; font-size: 20px; font-weight: bolder; color: #24292e;">Confirm by
                            verification code</h1>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <h4 style="font-size: 16px; margin: 0; color: #586069;">Please enter this verification code to
                            verify your email and get started on {{ site_url.name }}:<br/> <strong
                                    style="color: #24292e; font-size: 24px;">{{ verified_code }}</strong></h4>
                        <span style="font-size: 14px;">Verification codes expire after two hours.</span>
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <p style="color: #24292e; font-size: 14px;">You are receiving this email because you recently
                            created a new account on {{ site_url.name }}. If this was not you, please ignore this
                            email.</p>
                    </td>
                </tr>
                <tr>
                    <td style="margin-bottom: 10px">
                        <hr class="pn-horizontal-line"
                            style="height: 0; overflow: visible; border-top-color: #e1e4e8; color: #959da5; font-size: 12px; line-height: 18px; background-color: #d9d9d9; margin: 10px 0; border-style: solid none none; border-width: 1px 0 0;">
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 12px;">
                        <span>&copy;  {{ year }} <a href="//{{ site_url.domain }}"
                                                    style="text-decoration: none; color: #337ab7; padding-left:5px;"> {{ site_url.name }} </a><a
                                href="/privacy_policy "
                                style="text-decoration: none; color: #337ab7; padding: 0 5px;">Privacy</a>login on <a
                                href=" {% url 'user:login_url' %} "
                                style="text-decoration: none; color: #337ab7; padding-left: 5px;">{{ site_url.name }}</a></span>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
</body>
</html>

templates/form/login_form.html
{% extends 'main/base/base.html' %}
{% block content %}
    <div id="form-area">
        <div class="form-section">
            <div id="form">
                <form id="loginform" method="post">
                    <div class="form-logo">
                        <svg id="cp-logo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                             x="0px" y="0px"
                             viewBox="0 0 256 48" xml:space="preserve">
<polyline class="st0" points="151.2,10.5 133.8,10.5 133.8,37.6 151.2,37.6 "/>
                            <polyline class="st0" points="217,10.5 199.6,10.5 199.6,37.6 217,37.6 "/>
                            <line class="st0" x1="211.2" y1="24" x2="199.6" y2="24"/>
                            <line class="st0" x1="145.4" y1="24" x2="133.8" y2="24"/>
                            <polyline class="st0" points="232.5,37.5 232.5,10.4 253.8,37.5 253.8,10.4 "/>
                            <path class="st0" d="M166.7,25.9h11.6c4.3,0,7.7-3.5,7.7-7.7s-3.5-7.7-7.7-7.7h-11.6v27.1"/>
                            <path class="st0"
                                  d="M26.4,14.3c-2.5-2.5-5.8-3.9-9.7-3.9C9,10.5,3.2,16.3,3.2,24S9,37.5,16.8,37.5c3.9,0,7.2-1.5,9.7-3.9"/>
                            <path class="st0"
                                  d="M120.3,24c0,7.7-5.8,13.5-13.5,13.5H97V10.4h9.7C114.5,10.4,120.3,16.3,120.3,24L120.3,24z"/>
                            <path class="st1" d="M58.6,1.8L58,2.3c-1.3,1-2,2.6-2,4.3l0,35.3c0,1.7,0.7,3.3,2,4.3c1.8,1.4,4.3,1.4,6-0.1L86,27.9
	c1.2-1,1.9-2.6,1.9-4.2v-0.1c0-1.7-0.7-3.2-2-4.3L64.6,1.9C62.9,0.4,60.4,0.4,58.6,1.8z M34.2,21.8l13.2-10.2c0.8-0.6,1.8,0,1.8,1v3
	c0,0.4-0.2,0.7-0.4,0.9l-8.3,6.9v0.1l8.2,6.5c0.3,0.2,0.5,0.6,0.5,1v3.4c0,1-1.1,1.5-1.8,1L34.2,25.2c-0.3-0.2-0.5-0.6-0.5-1v-1.5
	C33.7,22.4,33.9,22,34.2,21.8z M65.4,11.6l12.4,10.2c0.3,0.2,0.4,0.6,0.4,1v1.5c0,0.4-0.2,0.7-0.4,1L65.4,35.4c-0.7,0.6-1.7,0-1.7-1
	V31c0-0.4,0.2-0.7,0.4-1l7.8-6.5v-0.1l-7.8-6.9c-0.3-0.2-0.4-0.6-0.4-0.9v-3C63.7,11.6,64.7,11.1,65.4,11.6z"/>
</svg>
                    </div>
                    <h4 class="form-title">Log In To {{ site_url.name }}</h4>
                    {% if request.COOKIES.success %}
                        <div class="form-success">
                            <span class="success">{{ request.COOKIES.success }}</span>
                        </div>
                    {% endif %}
                    {% if request.COOKIES.auth_error %}
                        <div class="form-error">
                            <span class="error">{{ request.COOKIES.auth_error }}</span>
                        </div>
                    {% endif %}
                    <div class="social-media-login">
                        <button type="button" class="google-login"><i
                                class="fab fa-google"></i><span>Log in with Google</span>
                        </button>
                        <button type="button" class="facebook-login"><i
                                class="fab fa-facebook-square"></i><span>Log In with Facebook</span></button>
                        <button type="button" class="twitter-login"><i
                                class="fab fa-twitter-square"></i><span>Log In with Twitter</span></button>
                        <button type="button" class="github-login"><i class="fab fa-github-square"></i><span>Log In with Github</span>
                        </button>
                    </div>
                    <div class="form-breaker">
                        <hr class="breaker">
                        <span>OR</span>
                        <hr class="breaker">
                    </div>
                    <div class="form-field-section">
                        <div>
                            <div class="form-field">
                                <i class="fas fa-user"></i>
                                <input type="text" name="username" class="username" id="username" value="{% if cookies_username %}{{ cookies_username }}{% elif username %}{{ username }}{% endif %}" placeholder="Enter your username" required>
                            </div>
                            {% if invalid_username %}
                                <div class="form-error">
                                    <span class="error">{{ invalid_username }}</span>
                                </div>
                            {% endif %}
                        </div>
                        <div>
                            <div class="form-field">
                                <i class="fas fa-lock"></i>
                                <input type="password" name="password"
                                       value="{% if cookies_password %}{{ cookies_password }}{% endif %}" class="password" id="password" placeholder="Enter your password" required>
                            </div>
                            {% if invalid_password %}
                                <div class="form-error">
                                    <span class="error">{{ invalid_password }}</span>
                                </div>
                            {% endif %}
                        </div>
                        <div class="remember-field">
                            <div class="remember-me">
                                    <input type="checkbox" name="rememberme" id="checkbox">
                                    <i class="fa-regular fa-circle"></i>
                                    <span>Remember Me</span>
                            </div>
                            <div id="forgot-password">
                                <a href="{% url 'user:forgot_password' %}"> Forgot Password? </a>
                            </div>
                        </div>
                        <div class="form-submit">
                            <button id="form-submit-button" type="submit">Log In</button>
                        </div>
                        <div class="form-breaker">
                            <hr class="breaker">
                        </div>
                        <div class="form-footer">
                            <div class="have-account"><span>Don't have and account? </span><a
                                    href="{% url 'user:signup_url' %}"> Sign Up </a></div>
                        </div>
                        {% csrf_token %}
                        <input type="hidden" name="login" id="submitted" value="true">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}