codepen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from codepen import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('', include('home.urls')),
    path('', include('user.urls')),
    path('', include('dashboard.urls')),
    path('', include('pen.urls')),
    path('', include('setting.urls')),
    path('404/', views.url_not_found, name='404'),
    path('search/', views.search, name='search'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'codepen.views.error_404'

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard_url"),
    path('dashboard/pens/', views.dashboard_pen, name='dashboard_pen'),
    path('dashboard/comments/', views.dashboard_comments, name='dashboard_comments'),
    path('dashboard/media/', views.dashboard_media, name='dashboard_media'),
    path('dashboard/profile/', views.dashboard_profile, name='dashboard_profile'),
    path('dashboard/followers/', views.dashboard_profile, name='dashboard_followers'),
    path('dashboard/following/', views.dashboard_profile, name='dashboard_following'),
    path('dashboard/profile/', views.dashboard_profile, name='dashboard_profile'),
    path('dashboard/profile/pen/', views.dashboard_profile, name='dashboard_profile_pens'),
    path('dashboard/profile/project/', views.dashboard_profile, name='dashboard_profile_project'),
    path('dashboard/profile/collection/', views.dashboard_profile, name='dashboard_profile_collection'),
    path('dashboard/upload-file/', views.upload_file, name='upload_file'),
    path('dashboard/activities/', views.activities, name="activities")
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home'),
    path('cookies/', views.work_with_cookies),
    path('check-email-sent', views.check_sent_email, name="email_sent")
]

pen/urls.py
from django.urls import path
from . import views

app_name = 'pen'
urlpatterns = [
    path('new-pen/', views.new_pen, name='new_pen'),
    path('<slug:username>/pen/<slug:pen_slug>/', views.single_pen, name='single_pen'),
    path('<slug:username>/pen/edit/', views.pen_edit, name="pen_edit"),
    path('<slug:username>/pen/delete/', views.pen_delete, name="pen_delete"),
    path('pen-filter/', views.pen_filter, name="pen_filter"),
    path('tag/<slug:tag_name>/', views.tag, name="tag"),
    path('pen/save/', views.vms_save_pen, name="save_pen"),
    path('pen/live-edit/', views.vms_live_edit, name="live_edit"),
    path('<slug:username>/pen/full/<slug:pen_slug>/', views.single_pen_full, name='single_pen'),
]

user/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'user'
urlpatterns = [
    path('login/', views.user_login, name="login_url"),
    path('signup/', views.signup, name="signup_url"),
    path('logout/', views.user_logout, name="logout_url"),
    path('auth/forgot-password/', views.forgot_password, name="forgot_password"),
    path('auth/change-password', views.change_password, name="change_password"),
    path('auth/change-password-token', views.change_password_token, name="change_password_token"),
    path('auth/change-password-code', views.change_password_code, name="change_password_code"),
    path('auth/change-password-resend-code', views.change_password_resend_code, name="change_password_resend_auth"),
    path('auth/verified-token', views.verified_token, name="auton_token"),
    path('auth/verified-code', views.verified_code, name="auton_code"),
    path('auth/verified-code-resend', views.verified_code_resend, name="verified_code_resend"),
    path('auth/user-validation', views.check_user_validation, name='user_validation')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
import json
from requests import get
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.contrib.sites.shortcuts import get_current_site
from codepen.functions import delete_cookie, get_client_ip, get_client_details_by_ip, home_url, user_auth, \
    codepen_platform, pen_platform
from codepen.cp_user import get_user, trending_pens
from profiles.models import Profile
from pen.models import Pen
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail


def index(request):
    site_url = get_current_site(request)
    ip = get_client_details_by_ip('103.239.255.44')

    context = {
        'site_url': site_url,
        'codepen_platform': pen_platform,
    }
    if ip:
        context['country'] = ip['countryCode']
    if request.method == "GET":
        if user_auth(request):
            login_user = get_user(request.user.id)
            context['login_user'] = login_user
            pen = Pen.objects.all()
            context['pens'] = pen
            context['username'] = login_user.get().username
            return render(request, 'main/home/index.html', context)
        else:
            login_user = get_user('guest_user')
            context['login_user'] = login_user
            trending_pen = trending_pens()[:6]
            context['trending_pens'] = trending_pen
            return render(request, 'main/home/index.html', context)
    else:
        return HttpResponseRedirect(home_url())


def work_with_cookies(request):
    auth_user = request.user.is_authenticated
    site_url = get_current_site(request)
    context = {
        'site_url': site_url,
        'auth_user': auth_user
    }
    templates = render(request, 'main/home/index.html', context)
    return templates


def check_sent_email(request):
    sent_main = send_mail('Test', 'Test django message', 'sohelhossenbijoy@gmail.com', ['sohelhossenbijoy@gmail.com'])
    if sent_main:
        print('ok')
        return HttpResponseRedirect(home_url())
    else:
        return HttpResponseRedirect(home_url())

user/views.py
import re
from datetime import date, datetime, timedelta
from django.utils import timezone
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.password_validation import CommonPasswordValidator
from django.contrib.auth.hashers import make_password
from django.contrib.sites.shortcuts import get_current_site
from django.views.decorators.csrf import csrf_exempt

from codepen.functions import user_validation, password_validation, email_validation, random_token, random_code, \
    admin_url, make_cookies_password, decode_cookies_password, name_validation, get_client_ip, get_client_details_by_ip, \
    dashboard_url, password_helper_text, home_url, user_auth
from codepen.cp_user import get_user, get_user_by_code, get_user_by_token
from django.utils.html import strip_tags
from codepen.settings import EMAIL_HOST_USER, COOKIE_MAX_AGE
from .models import User, UserLogs

username_validator = UnicodeUsernameValidator
password_validator = CommonPasswordValidator


# Create your views here.
def user_login(request):
    site_url = get_current_site(request)
    context = {
        'site_url': site_url,
    }
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect(dashboard_url())
        cookies_username = request.COOKIES.get('username')
        cookies_password = request.COOKIES.get('password')
        if cookies_username:
            context['cookies_username'] = cookies_username
        if cookies_password:
            context['cookies_password'] = decode_cookies_password(cookies_password)
        return render(request, 'form/login_form.html', context)
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        rememberme = request.POST.get('rememberme')
        redirect_url = request.GET.get('next')
        user_details = get_user(username)
        if user_details:
            auth_email = user_details.get().email
            if user_details.get().check_password(password):
                user_auth = authenticate(request, email=auth_email, password=password)
                if user_auth is not None:
                    login(request, user_auth)
                    user_ip = get_client_ip(request)
                    user_details_by_ip = get_client_details_by_ip(user_ip)
                    current_time = datetime.now()
                    if user_details_by_ip['status'] == 'success':
                        user_country = user_details_by_ip['country']
                        user_city = user_details_by_ip['city']
                        UserLogs.objects.create(user_id=user_details.get().id, user_country=user_country,
                                                user_city=user_city,
                                                user_login=current_time, user_ip=user_ip)
                    else:
                        UserLogs.objects.create(user_id=user_details.get().id, user_login=current_time,
                                                user_ip=user_ip)
                    delete_user_log = UserLogs.objects.all().filter(user_login__lte=datetime.now() - timedelta(30))

                    if delete_user_log:
                        delete_user_log.delete()
                    login_template = HttpResponseRedirect(dashboard_url())
                    login_template.delete_cookie('success')
                    login_template.delete_cookie('auth_error')
                    if rememberme:
                        hash_password = make_cookies_password(password)
                        login_template.set_cookie('password', hash_password, max_age=COOKIE_MAX_AGE)
                        login_template.set_cookie('username', username, max_age=COOKIE_MAX_AGE)
                    else:
                        login_template.delete_cookie('password')
                        login_template.delete_cookie('username')
                    if redirect_url:
                        login_template = HttpResponseRedirect(redirect_url)
                    return login_template
            else:
                context['invalid_password'] = 'password did not match'
                render_template = render(request, 'form/login_form.html', context)
                return render_template
        else:
            if re.search(r'@', username):
                context['invalid_username'] = f"{username} is incorrect email or didn't exists"
            else:
                context['invalid_username'] = f"{username} is incorrect username or didn't exists"
        render_template = render(request, 'form/login_form.html', context)
        return render_template
    else:
        return HttpResponseRedirect(home_url())


def signup(request):
    site_url = get_current_site(request)
    if request.method == 'GET':
        if user_auth(request):
            return redirect(dashboard_url())
        context = {
            'site_url': site_url,
            'password_helper': password_helper_text()
        }
        return render(request, 'form/signup_form.html', context)
    elif request.method == "POST":
        context = {
            'site_url': site_url,
        }
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        cpassword = request.POST.get('cpassword')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')

        if username and user_validation(username):
            user = get_user(username)
            if user:
                context['username_error'] = f'{username} already exists.'
            else:
                context['username'] = username
        else:
            context['username_error'] = "Username only contain Letters, digits and _ only."

        if email and email_validation(email):
            user_email = get_user(email)
            if user_email:
                context['email_error'] = f'{email} already exits.'
            else:
                context['email'] = email
        else:
            context['email_error'] = "Invalid email address."

        if password != cpassword:
            context['password_error'] = "Those passwords didn't match."
        elif password and not password_validation(password):
            context['password_error'] = password_helper_text()
        else:
            context['password'] = password

        if first_name and not name_validation(first_name):
            context['fname_error'] = "First name validation error"
        else:
            context['fname'] = first_name

        if last_name and not name_validation(last_name):
            context['lname_error'] = "Last name validation error"
        else:
            context['lname'] = last_name

        if username and user_validation(username) and not get_user(username) and email and email_validation(
                email) and not get_user(email) and password and password_validation(
                password) and password == cpassword and first_name and last_name:
            create_user = User.objects.create_user(username=username, email=email, password=password,
                                                   first_name=first_name, last_name=last_name)
            if create_user:
                verified_code = random_code(111111, 999999)
                verified_token = random_token(32)
                get_date = date.today()
                year = get_date.strftime("%Y")
                update_user = get_user(username)
                update_user.update(user_activation_key=verified_token, user_verification_code=verified_code)
                email_context = {
                    'site_url': site_url,
                    'username': first_name,
                    'email': email,
                    'verified_code': verified_code,
                    'verified_token_url': f'{site_url.domain}/auth/verified-token?token={verified_token}',
                    'year': year
                }
                template = render_to_string('form/login_email_template.html', email_context)
                email_template = strip_tags(template)
                subject = f'{first_name} verify your {site_url.name} account'

                mail = EmailMultiAlternatives(subject, email_template, EMAIL_HOST_USER, [email])
                mail.fail_silently = True
                mail.attach_alternative(template, 'text/html')

                if mail.send():
                    signup_template = HttpResponseRedirect('/auth/verified-code')
                    signup_template.set_cookie('success',
                                               'Your account create successfully. Please verify your account')
                    return signup_template
            else:
                context['auth_error'] = "Something went to wrong to create your account. Please try again"
        else:
            context[
                'auth_error'] = "Something went to wrong to create your account. Please check the error and try again"
        render_template = render(request, 'form/signup_form.html', context)
        return render_template
    else:
        return redirect(home_url())


def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('/')
    else:
        return redirect('/login')


def verified_code(request):
    site_url = get_current_site(request)
    if request.user.is_authenticated:
        return redirect('dashboard_url')
    else:
        context = {
            'site_url': site_url,
            'form_name': "Verification Code",
            'resend_url': '/auth/verified-code-resend'
        }

templates/main/home/index.html
{% extends 'main/base/base.html' %}
{% block content %}
    <div class="main-content">
    {% if request.user.is_authenticated %}
        {% include 'main/home/user.html' %}
        {% else %}
        {% include 'main/home/global.html' %}
    {% endif %}
    </div>
{% endblock %}

templates/main/home/user.html
{% load dynamic %}
{% load static %}
{% block content %}
    <div id="home-pen-wrapper" class="home-pen-wrapper">
        <div id="pen-content-wrap">
            <div class="pen-filter-wrapper" id="pen-filter-wrapper">
                <ul class="filter-wrap">
                    <li class="pens active"><a href="{% url 'dashboard:dashboard_profile_pens' %}">Pens</a></li>
                    <li class="project"><a href="{% url 'dashboard:dashboard_profile_project' %}">Project</a></li>
                    <li class="collection"><a href="{% url 'dashboard:dashboard_profile_collection' %}">Collection</a>
                    </li>
                </ul>
                <div class="pen-filter-content">
                    <ul class="pen-filter-list">
                        <li class="all-pens active"><a href="{% url 'dashboard:dashboard_profile_pens' %}?all-pens">All
                            Pens</a></li>
                        <li class="popular-pens"><a
                                href="{% url 'dashboard:dashboard_profile_pens' %}?popular">Popular</a></li>
                        <li class="all-pens"><a href="{% url 'dashboard:dashboard_profile_pens' %}?public">Trending</a>
                        </li>
                        <li class="all-pens">
                            <select id="pen-by-languages">
                                <option value="" selected="selected">Select Language</option>
                                {% for key, values in codepen_platform.items %}
                                    <option class="languages" value="{{ key }}">
                                        <a href="{% url 'pen:pen_filter' %}?languages={{ key }}" class="menu-link"><i class="{{ values.icon }}"></i> {{ values.name }}</a>
                                    </option>
                                {% endfor %}
                            </select>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="pen-content" id="pen-content-wrapper">
                {% for pen in pens %}
                    <article class="single-item single-pen" id="pen-{{ pen.id }}">
                        <div class="pen-preview-wrapper">
                            <div class="pen-preview">
                                <a class="pen-link" href="/{{ pen.user.username }}/pen/{{ pen.pen_slug }}">
                                    <div class="preview-source">
                                        {% if pen.pen_type == 'html' or pen.pen_type == 'javascript' %}
                                            <iframe src="/{{ username }}/details/{{ pen.pen_slug }}"></iframe>
                                        {% elif pen.pen_type == 'cpp' %}
                                            <i class="fa-solid fa-square-c"></i>
                                        {% elif pen.pen_type == 'php' %}
                                            <i class="fa-brands fa-php"></i>
                                        {% elif pen.pen_type == 'python' %}
                                            <i class="fa-brands fa-python"></i>
                                        {% elif pen.pen_type == 'java' %}
                                            <i class="fa-brands fa-java"></i>
                                        {% elif pen.pen_type == 'r' %}
                                            <i class="fa-brands fa-r-project"></i>
                                        {% elif pen.pen_type == 'go' %}
                                            <i class="fa-brands fa-golang"></i>
                                        {% elif pen.pen_type == 'ruby' %}
                                            <i class="fa-solid fa-gem"></i>
                                        {% elif pen.pen_type == 'vue' %}
                                            <i class="fa-brands fa-vuejs"></i>
                                        {% elif pen.pen_type == 'react' %}
                                            <i class="fa-brands fa-react"></i>
                                        {% elif pen.pen_type == 'xml' %}
                                            <i class="fa-brands fa-html5"></i>
                                        {% elif pen.pen_type == 'javascript' %}
                                            <i class="fa-brands fa-js-square"></i>
                                        {% else %}
                                            <i class="fa-solid fa-file-code"></i>
                                        {% endif %}
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="pen-content">
                            <header class="pen-header">
                                <div class="pen-title">
                                    <h2 class="title" title="{{ pen.pen_title }}">
                                        {% if pen.pen_title|length > 30 %}
                                            <a href="/ {% url 'pen:single_pen'  pen.use.username  pen.pen_slug %}">{{ pen.pen_title|slice:'0:30' }}...</a>
                                        {% else %}
                                            <a href="/{{ pen.user.username }}/pen/{{ pen.pen_slug }}">{{ pen.pen_title }}</a>
                                        {% endif %}
                                    </h2>
                                </div>
                                <div class="pen-option-wrap">
                                    <i class="fa-solid fa-ellipsis"></i>
                                    <ul class="pen-option-menu">
                                        <li class="pen-option">
                                            <button class="collection" data-id="{{ pen.id }}">Add to Collection</button>
                                        </li>
                                        <li class="pen-option">
                                            <button class="private" data-id="{{ pen.id }}">Make Private</button>
                                        </li>
                                        <li class="pen-option">
                                            <button class="delete" data-id="{{ pen.id }}">Delete</button>
                                        </li>
                                    </ul>
                                </div>
                            </header>
                            <footer class="pen-footer">
                                <button title="Love" class="pen-love" id="pen-love">
                                    <i class="fa-regular fa-heart"></i>
                                    <span class="love">{{ pen.pen_love.all.count }}</span>
                                </button>
                                <a href="/{{ username }}/pen/details/{{ pen.pen_slug }}/" class="pen-comment">
                                    <i class="fa-regular fa-comment-dots"></i>
                                    <span class="comments">{{ pen.pen_comments }}</span>
                                </a>
                                <a href="/{{ username }}/pen/full/{{ pen.pen_slug }}" class="pen-view">
                                    <i class="fa-regular fa-eye"></i>
                                    <span class="view">{{ pen.pen_view.all.count }}</span>
                                </a>
                            </footer>
                        </div>
                    </article>
                {% endfor %}
            </div>
            <div class="load-more-wrapper loading-spinner">
                <button type="button" class="load-more"><i class="fa fa-spinner"></i> <span>More pen</span></button>
            </div>
        </div>
    </div>
{% endblock %}