codepen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from codepen import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('', include('home.urls')),
    path('', include('user.urls')),
    path('', include('dashboard.urls')),
    path('', include('pen.urls')),
    path('', include('setting.urls')),
    path('404/', views.url_not_found, name='404'),
    path('search/', views.search, name='search'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'codepen.views.error_404'

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard_url"),
    path('dashboard/pens/', views.dashboard_pen, name='dashboard_pen'),
    path('dashboard/comments/', views.dashboard_comments, name='dashboard_comments'),
    path('dashboard/media/', views.dashboard_media, name='dashboard_media'),
    path('dashboard/profile/', views.dashboard_profile, name='dashboard_profile'),
    path('dashboard/followers/', views.dashboard_profile, name='dashboard_followers'),
    path('dashboard/following/', views.dashboard_profile, name='dashboard_following'),
    path('dashboard/profile/', views.dashboard_profile, name='dashboard_profile'),
    path('dashboard/profile/pen/', views.dashboard_profile, name='dashboard_profile_pens'),
    path('dashboard/profile/project/', views.dashboard_profile, name='dashboard_profile_project'),
    path('dashboard/profile/collection/', views.dashboard_profile, name='dashboard_profile_collection'),
    path('dashboard/upload-file/', views.upload_file, name='upload_file'),
    path('dashboard/activities/', views.activities, name="activities")
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home'),
    path('cookies/', views.work_with_cookies),
    path('check-email-sent', views.check_sent_email, name="email_sent")
]

pen/urls.py
from django.urls import path
from . import views

app_name = 'pen'
urlpatterns = [
    path('new-pen/', views.new_pen, name='new_pen'),
    path('<slug:username>/pen/<slug:pen_slug>/', views.single_pen, name='single_pen'),
    path('<slug:username>/pen/edit/', views.pen_edit, name="pen_edit"),
    path('<slug:username>/pen/delete/', views.pen_delete, name="pen_delete"),
    path('pen-filter/', views.pen_filter, name="pen_filter"),
    path('tag/<slug:tag_name>/', views.tag, name="tag"),
    path('pen/save/', views.vms_save_pen, name="save_pen"),
    path('pen/live-edit/', views.vms_live_edit, name="live_edit"),
    path('<slug:username>/pen/full/<slug:pen_slug>/', views.single_pen_full, name='single_pen'),
]

dashboard/models.py
from django.db import models

# Create your models here.
from codepen.functions import upload_path
from user.models import User


class Media(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file_title = models.CharField(max_length=100, null=False, blank=False)
    file_description = models.TextField()
    file_name = models.CharField(max_length=100, null=False, blank=False)
    file_url = models.FileField(null=False, blank=False, upload_to=upload_path, unique=True, max_length=200)
    file_size = models.BigIntegerField(null=False, blank=False)
    mime_type = models.CharField(max_length=100, null=False, blank=False)
    uploaded_date = models.DateTimeField(auto_now=True)
    uploaded_modified = models.DateTimeField(auto_now_add=True)

home/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.files import storage
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from codepen.cp_user import get_profile, get_user
from codepen.functions import create_file_directory, get_mime_type, new_name, get_client_ip, \
    get_client_details_by_ip
from codepen.settings import MEDIA_URL
from pen.models import Pen, Comment, PenData
from user.models import User, UserLogs
from .models import Media


@login_required
@csrf_exempt
def dashboard(request):
    user = request.user
    profile = get_profile(user.username)
    all_pen = Pen.objects.all().filter(user_id=user.id).order_by('-id')
    all_comments = Comment.objects.all().filter(user_id=user.id).order_by('-id')
    publish_pen = all_pen.filter(pen_status='published')
    private_pen = all_pen.filter(pen_status='private')
    draft_pen = all_pen.filter(pen_status='draft')
    trash_pen = all_pen.filter(pen_status='trash')
    login_status = UserLogs.objects.all().filter(user_id=user.id).order_by('-id')

    context = {
        'user_id': user.id,
        'username': user.username,
        'user': user,
        'current_path_name': request.path_info[1:-1],
        'current_path': request.path[1:-1],
        'all_pen': all_pen,
        'publish_pen': publish_pen,
        'private_pen': private_pen,
        'draft_pen': draft_pen,
        'trash_pen': trash_pen,
        'all_comments': all_comments,
        'login_status': login_status,
        'profile': profile
    }
    render_template = render(request, 'dashboard/home/dashboard.html', context)
    return render_template


@login_required
@csrf_exempt
def dashboard_pen(request):
    user = request.user
    profile = get_profile(user.username)
    all_pen = Pen.objects.all().filter(user_id=user.id)
    all_comments = Comment.objects.all().filter(user_id=user.id)
    publish_pen = all_pen.filter(pen_status='published')
    private_pen = all_pen.filter(pen_status='private')
    draft_pen = all_pen.filter(pen_status='draft')
    trash_pen = all_pen.filter(pen_status='trash')

    context = {
        'user_id': user.id,
        'username': user.username,
        'user': user,
        'current_path_name': request.path_info[1:-1],
        'current_path': request.path[1:-1],
        'all_pen': all_pen,
        'all_comments': all_comments,
        'publish_pen': publish_pen,
        'private_pen': private_pen,
        'draft_pen': draft_pen,
        'trash_pen': trash_pen,
        'profile': profile
    }

    render_template = render(request, 'dashboard/pen/pen.html', context)
    return render_template


@login_required
@csrf_exempt
def dashboard_comments(request):
    user = request.user
    username = user.username
    profile = get_profile(username)
    all_comments = Comment.objects.all().filter(user_id=user.id)

    context = {
        'user_id': user.id,
        'username': username,
        'user': user,
        'current_path_name': request.path_info[1:-1],
        'current_path': request.path[1:-1],
        'all_comments': all_comments,
        'profile': profile
    }

    render_template = render(request, 'dashboard/comment/comments.html', context)
    return render_template


@login_required
@csrf_exempt
def dashboard_media(request):
    user = request.user
    mime_type = get_mime_type()
    img_mime_type = ['.gif', '.jpg', '.jpe', '.jpeg', '.png', 'webp', '.svg']
    video_mime_type = ['.mp4', '.mpeg', '.m1v', '.mpa', '.mpe', '.mpg', '.mov', '.qt', '.webm', '.avi', '.movie']
    username = user.username
    profile = get_profile(username)
    all_media_list = Media.objects.all().filter(user_id=user.id).order_by('-id')
    paginate_media = Paginator(all_media_list, 36)
    current_page = request.GET.get('page')
    media_list = paginate_media.get_page(current_page)
    context = {
        'user_id': user.id,
        'username': username,
        'current_path_name': request.path_info[1:-1],
        'current_path': request.path[1:-1],
        'url': request.get_host(),
        'mime': ','.join(mime_type),
        'img_mime_type': img_mime_type,
        'video_mime_type': video_mime_type,
        'media_list': media_list,
        'pagination': paginate_media,
        'profile': profile
    }
    render_template = render(request, 'dashboard/media/media.html', context)
    return render_template


@csrf_exempt
def upload_file(request):
    file = request.FILES.get('file')
    directory = create_file_directory(request)
    domain = get_current_site(request).domain
    user = int(request.user.id)
    file_title = file.name
    file_name = storage.get_valid_filename(file_title)
    only_name = file_name[:file_name.rfind('.')]
    file_url = f'{MEDIA_URL}{directory}/{file_name}'
    file_size = file.size
    file_mime = file.content_type
    file_ext = f".{file_name.split('.').pop()}"
    if file_mime == '':
        file_mime = 'unattached'

    if file_ext in get_mime_type():
        get_media = Media.objects.all()
        if get_media.filter(file_url__icontains=only_name):
            count_file = get_media.filter(file_url__icontains=only_name).count()
            name = new_name(file_name, count_file)
            new_url = f'{MEDIA_URL}{directory}/{name}'
            location = f'{directory}/{name}'
            upload_media = Media.objects.create(user_id=user, file_title=file_title, file_name=name, file_url=new_url,
                                                file_size=file_size, mime_type=file_mime)
            if upload_media:
                file_id = upload_media.id
                save_files = storage.FileSystemStorage()
                save_files.save(location, file)
                return JsonResponse({'file_id': file_id, 'file_url': new_url, 'file_name': name})
        else:
            upload_media = Media.objects.create(user_id=user, file_title=file_title, file_name=file_name,
                                                file_url=file_url, file_size=file_size, mime_type=file_mime)
            if upload_media:
                file_id = upload_media.id
                location = f'{directory}/{file_name}'
                save_files = storage.FileSystemStorage()
                save_files.save(location, file)
                return JsonResponse({'file_id': file_id, 'file_url': file_url, 'file_name': file_name})
    else:
        return False
    return JsonResponse({'file_url': file_url, 'file_name': file_name})


@login_required
def dashboard_profile(request):
    user = get_user(request.user.id)
    username = user.get().username
    ip = get_client_ip(request)
    profile = get_profile(username)
    pens = Pen.objects.all().filter(user_id=user.get().id)
    pen_data = PenData.objects.all()
    comments = Comment.objects.all().filter(user_id=user.get().id)

    for pen in pens:
        var = pen.pen_love.all().count

    if profile and profile.get().screen_name:
        screen_name = profile.get().screen_name
    else:
        screen_name = request.user.get_full_name()
    if ip != '':
        user_details = get_client_details_by_ip('103.239.255.44')

    context = {
        'user_id': user.get().id,
        'username': username,
        'current_path_name': request.path_info[1:-1],
        'current_path': request.path[1:-1],
        'location': user_details['country'],
        'screen_name': screen_name,
        'profile': profile,
        'follower': user.get().follower.count(),
        'following': user.get().following.count(),
        'pens': pens,
        'pen_data': pen_data,
        'comments': comments,
    }
    if profile:
        context['social_links'] = profile.get().profile_links

    render_template = render(request, 'dashboard/profile/profile.html', context)
    return render_template


@login_required
def activities(request):
    user = get_user(request.user.id)
    username = user.get().username
    profile = get_profile(username)
    context = {
        'user_id': user.get().id,
        'username': username,
        'current_path_name': request.path_info[1:-1],
        'current_path': request.path[1:-1],
        'profile': profile
    }

    render_template = render(request, 'dashboard/profile/profile.html', context)
    return render_template

home/views.py
import json
from requests import get
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.contrib.sites.shortcuts import get_current_site
from codepen.functions import delete_cookie, get_client_ip, get_client_details_by_ip, home_url, user_auth, \
    codepen_platform, pen_platform
from codepen.cp_user import get_user, trending_pens
from profiles.models import Profile
from pen.models import Pen
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail


def index(request):
    site_url = get_current_site(request)
    ip = get_client_details_by_ip('103.239.255.44')

    context = {
        'site_url': site_url,
        'codepen_platform': pen_platform,
    }
    if ip:
        context['country'] = ip['countryCode']
    if request.method == "GET":
        if user_auth(request):
            login_user = get_user(request.user.id)
            context['login_user'] = login_user
            pen = Pen.objects.all()
            context['pens'] = pen
            context['username'] = login_user.get().username
            return render(request, 'main/home/index.html', context)
        else:
            login_user = get_user('guest_user')
            context['login_user'] = login_user
            trending_pen = trending_pens()[:6]
            context['trending_pens'] = trending_pen
            return render(request, 'main/home/index.html', context)
    else:
        return HttpResponseRedirect(home_url())


def work_with_cookies(request):
    auth_user = request.user.is_authenticated
    site_url = get_current_site(request)
    context = {
        'site_url': site_url,
        'auth_user': auth_user
    }
    templates = render(request, 'main/home/index.html', context)
    return templates


def check_sent_email(request):
    sent_main = send_mail('Test', 'Test django message', 'sohelhossenbijoy@gmail.com', ['sohelhossenbijoy@gmail.com'])
    if sent_main:
        print('ok')
        return HttpResponseRedirect(home_url())
    else:
        return HttpResponseRedirect(home_url())

templates/dashboard/home/dashboard.html
{% extends 'dashboard/base/base.html' %}
{% load dynamic %}
{% block content %}
    <div id="dashboard-widgets-wrap" class="dashboard-widgets-wrap">
        <div class="left-widget">
            <div class="dashboard-widget">
                <div class="widget-header"><h2 class="header">At a Glance</h2> <i
                        class="fa fa-angle-up"></i></div>
                <div class="widget-content glance">
                    <a href="/dashboard/pens/?pen_status=all" class="all-pen">
                        <svg id="pen-edit-icon" xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 576 512"
                             xml:space="preserve">
                                <path class="st0"
                                      d="M417.8,315.5l20-20c3.8-3.8,10.2-1.1,10.2,4.2V464c0,26.5-21.5,48-48,48H48c-26.5,0-48-21.5-48-48V112c0-26.5,21.5-48,48-48h292.3c5.3,0,8,6.5,4.2,10.2l-20,20c-1.1,1.1-2.7,1.8-4.2,1.8H48c-8.8,0-16,7.2-16,16v352c0,8.8,7.2,16,16,16h352c8.8,0,16-7.2,16-16V319.7C416,318.1,416.6,316.6,417.8,315.5z M563.7,124.3L251.2,436.8l-99.9,11.1c-13.4,1.5-24.7-9.8-23.2-23.2l11.1-99.9L451.7,12.3c16.4-16.4,43-16.4,59.4,0l52.6,52.6C580.1,81.3,580.1,107.9,563.7,124.3L563.7,124.3z M470.1,172.7L403.4,106L169.8,339.5l-8.3,75.1l75.1-8.3L470.1,172.7L470.1,172.7z M541.1,87.5l-52.6-52.6c-3.8-3.8-10.2-4-14.1,0L426,83.3l66.7,66.7l48.4-48.4C545,97.8,545,91.4,541.1,87.5L541.1,87.5z"></path>
                            </svg>
                        <span>{{ all_pen.count }} Pen</span>
                    </a>
                    <a href="/dashboard/pens/?pen_status=published" class="publish-pen">
                        <svg id="pen-edit-icon" xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 576 512"
                             xml:space="preserve">
                                <path class="st0"
                                      d="M417.8,315.5l20-20c3.8-3.8,10.2-1.1,10.2,4.2V464c0,26.5-21.5,48-48,48H48c-26.5,0-48-21.5-48-48V112c0-26.5,21.5-48,48-48h292.3c5.3,0,8,6.5,4.2,10.2l-20,20c-1.1,1.1-2.7,1.8-4.2,1.8H48c-8.8,0-16,7.2-16,16v352c0,8.8,7.2,16,16,16h352c8.8,0,16-7.2,16-16V319.7C416,318.1,416.6,316.6,417.8,315.5z M563.7,124.3L251.2,436.8l-99.9,11.1c-13.4,1.5-24.7-9.8-23.2-23.2l11.1-99.9L451.7,12.3c16.4-16.4,43-16.4,59.4,0l52.6,52.6C580.1,81.3,580.1,107.9,563.7,124.3L563.7,124.3z M470.1,172.7L403.4,106L169.8,339.5l-8.3,75.1l75.1-8.3L470.1,172.7L470.1,172.7z M541.1,87.5l-52.6-52.6c-3.8-3.8-10.2-4-14.1,0L426,83.3l66.7,66.7l48.4-48.4C545,97.8,545,91.4,541.1,87.5L541.1,87.5z"></path>
                            </svg>
                        <span>{{ publish_pen.count }} Publish Pen</span>
                    </a>
                    <a href="/dashboard/pens/?pen_status=private" class="private-pen">
                        <svg id="pen-edit-icon" xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 576 512"
                             xml:space="preserve">
                                <path class="st0"
                                      d="M417.8,315.5l20-20c3.8-3.8,10.2-1.1,10.2,4.2V464c0,26.5-21.5,48-48,48H48c-26.5,0-48-21.5-48-48V112c0-26.5,21.5-48,48-48h292.3c5.3,0,8,6.5,4.2,10.2l-20,20c-1.1,1.1-2.7,1.8-4.2,1.8H48c-8.8,0-16,7.2-16,16v352c0,8.8,7.2,16,16,16h352c8.8,0,16-7.2,16-16V319.7C416,318.1,416.6,316.6,417.8,315.5z M563.7,124.3L251.2,436.8l-99.9,11.1c-13.4,1.5-24.7-9.8-23.2-23.2l11.1-99.9L451.7,12.3c16.4-16.4,43-16.4,59.4,0l52.6,52.6C580.1,81.3,580.1,107.9,563.7,124.3L563.7,124.3z M470.1,172.7L403.4,106L169.8,339.5l-8.3,75.1l75.1-8.3L470.1,172.7L470.1,172.7z M541.1,87.5l-52.6-52.6c-3.8-3.8-10.2-4-14.1,0L426,83.3l66.7,66.7l48.4-48.4C545,97.8,545,91.4,541.1,87.5L541.1,87.5z"></path>
                            </svg>
                        <span>{{ private_pen.count }} Private Pen</span>
                    </a>
                    <a href="/dashboard/pens/?pen_status=draft" class="draft-pen">
                        <svg id="pen-edit-icon" xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 576 512"
                             xml:space="preserve">
                                <path class="st0"
                                      d="M417.8,315.5l20-20c3.8-3.8,10.2-1.1,10.2,4.2V464c0,26.5-21.5,48-48,48H48c-26.5,0-48-21.5-48-48V112c0-26.5,21.5-48,48-48h292.3c5.3,0,8,6.5,4.2,10.2l-20,20c-1.1,1.1-2.7,1.8-4.2,1.8H48c-8.8,0-16,7.2-16,16v352c0,8.8,7.2,16,16,16h352c8.8,0,16-7.2,16-16V319.7C416,318.1,416.6,316.6,417.8,315.5z M563.7,124.3L251.2,436.8l-99.9,11.1c-13.4,1.5-24.7-9.8-23.2-23.2l11.1-99.9L451.7,12.3c16.4-16.4,43-16.4,59.4,0l52.6,52.6C580.1,81.3,580.1,107.9,563.7,124.3L563.7,124.3z M470.1,172.7L403.4,106L169.8,339.5l-8.3,75.1l75.1-8.3L470.1,172.7L470.1,172.7z M541.1,87.5l-52.6-52.6c-3.8-3.8-10.2-4-14.1,0L426,83.3l66.7,66.7l48.4-48.4C545,97.8,545,91.4,541.1,87.5L541.1,87.5z"></path>
                            </svg>
                        <span>{{ draft_pen.count }} Draft Pen</span>
                    </a>
                    <a href="/dashboard/pens/?pen_status=trash" class="trash-pen">
                        <svg id="pen-edit-icon" xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 576 512"
                             xml:space="preserve">
                                <path class="st0"
                                      d="M417.8,315.5l20-20c3.8-3.8,10.2-1.1,10.2,4.2V464c0,26.5-21.5,48-48,48H48c-26.5,0-48-21.5-48-48V112c0-26.5,21.5-48,48-48h292.3c5.3,0,8,6.5,4.2,10.2l-20,20c-1.1,1.1-2.7,1.8-4.2,1.8H48c-8.8,0-16,7.2-16,16v352c0,8.8,7.2,16,16,16h352c8.8,0,16-7.2,16-16V319.7C416,318.1,416.6,316.6,417.8,315.5z M563.7,124.3L251.2,436.8l-99.9,11.1c-13.4,1.5-24.7-9.8-23.2-23.2l11.1-99.9L451.7,12.3c16.4-16.4,43-16.4,59.4,0l52.6,52.6C580.1,81.3,580.1,107.9,563.7,124.3L563.7,124.3z M470.1,172.7L403.4,106L169.8,339.5l-8.3,75.1l75.1-8.3L470.1,172.7L470.1,172.7z M541.1,87.5l-52.6-52.6c-3.8-3.8-10.2-4-14.1,0L426,83.3l66.7,66.7l48.4-48.4C545,97.8,545,91.4,541.1,87.5L541.1,87.5z"></path>
                            </svg>
                        <span>{{ trash_pen.count }} Trash Pen</span>
                    </a>
                    <div class="comment-pen">
                        <a href="/dashboard/comments/">
                            <svg id="comment-icon" xmlns="http://www.w3.org/2000/svg"
                                 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                 viewBox="0 0 512 512" xml:space="preserve">
                            <path class="st0"
                                  d="M256,31.1c-141.4,0-255.1,93.1-255.1,208c0,47.6,19.9,91.2,52.9,126.3c-14.9,39.5-45.9,72.9-46.4,73.2c-6.6,7-8.4,17.2-4.6,26c3,9.6,11.6,15.3,21.2,15.3c61.5,0,109.1-25.8,139.1-46.2c28.1,9,60.2,14.2,92.9,14.2c141.4,0,255.1-93.1,255.1-207.1S397.4,31.1,256,31.1z M256,416c-28.2,0-56.2-4.2-83.2-12.8c-9.5-3.1-19.9-1.5-28.1,4.3c-22.1,16.2-58.5,35.3-102.7,39.7c11.1-15.1,29.8-40.5,40.7-69.6l0.1-0.3c4.3-11.3,1.8-23.1-6.4-32.8C47.5,313.1,32.1,277.6,32.1,240c0-97,100.5-176,223.1-176c123.5,0,223.1,79,223.1,176S379.5,416,256,416z M256,216c-13.2,0-24,10.7-24,24c0,13.2,10.8,24,24,24s24-10.8,24-24C280,226.7,269.3,216,256,216z M384,216c-13.2,0-24,10.7-24,24c0,13.2,10.8,24,24,24s24-10.8,24-24C408,226.7,397.3,216,384,216z M128,216c-13.2,0-24,10.7-24,24c0,13.2,10.8,24,24,24s24-10.7,24-24S141.3,216,128,216z"></path>
                        </svg>
                            <span>{{ all_comments.count }} Comments</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="dashboard-widget">
                <div class="widget-header"><h2 class="header">Recent Pen</h2> <i
                        class="fa fa-angle-up"></i></div>
                <div class="widget-content recent-pen">
                    <ul class="all-pen">
                        {% for pen in all_pen|slice:'0:5' %}
                            <li>
                                <a href="{% url 'pen:single_pen' username pen.pen_slug %}">
                                    <p class="pen-title">{{ pen.pen_title|word_slice:'0:10' }}</p>
                                    <span class="pen-published">
                                    {% if pen.modefied %}
                                        {{ pen.modified }}
                                    {% else %}
                                        {{ pen.pen_published }}
                                    {% endif %}
                                </span>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="dashboard-widget">
                <div class="widget-header"><h2 class="header">Recent Comments</h2> <i
                        class="fa fa-angle-up"></i></div>
                <div class="widget-content recent-comment">
                    <ul class="all-comment">
                        {% for comment in all_comments|slice:'0:5' %}
                            <li>
                                <a href="{% url 'pen:single_pen' username comment.pen.pen_slug %}#comment-{{ comment.id }}">
                                    <p class="comment-content">{{ comment.comment_content|word_slice:'0:10' }}</p>
                                    <span class="comment-publish">
                                        {% if comment.comment_modified %}
                                            {{ comment.comment_modified }}
                                        {% else %}
                                            {{ comment.comment_publish }}
                                        {% endif %}
                                    </span>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="dashboard-widget">
                <div class="widget-header"><h2 class="header">Recent Login Status</h2> <i
                        class="fa fa-angle-up"></i></div>
                <div class="widget-content recent-login-status">
                    <ul class="login-status">
                        {% for status in login_status|slice:'0:5' %}
                            <li>
                                <a href="{% url 'dashboard:activities' %}#login-{{ status.id }}">
                                    <span class="login-date">{{ status.user_login }}</span>
                                    <span class="username">{{ status.user.username }}</span>
                                    <span class="ip">{{ status.user_ip }}</span>
                                    {% if status.user_country or status.user_city %}
                                        <span class="user-location">{{ status.user_city }}, {{ status.user_country }}</span>
                                    {% endif %}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="right-widget">
            <div class="dashboard-widget">
                <div class="widget-header"><h2 class="header">Add Quick Pen</h2> <i
                        class="fa fa-angle-up"></i></div>
                <div class="form-section">
                    <form name="post" action="{% url 'pen:new_pen' %}" method="post" id="quick-press"
                          class="initial-form hide-if-no-js">
                        <div class="form-field" id="title-wrap">
                            <label for="title">
                                Title </label>
                            <input type="text" name="title" id="title">
                        </div>

                        <div class="form-field" id="pen-description">
                            <label for="description">Description</label>
                            <textarea name="description" id="description" placeholder="What’s on your mind?"
                                      class="description" rows="6" cols="15"></textarea>
                        </div>

                        <div class="form-field">
                            <select class="pen-status">
                                <option value="publish" selected>Publish</option>
                                <option value="draft">Draft</option>
                            </select>
                        </div>

                        <div class="form-submit">
                            <button class="submit">Add Pen</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="dashboard-widget">
                <div class="widget-header"><h2 class="header">Quick Links</h2> <i
                        class="fa fa-angle-up"></i></div>
                <div class="widget-content quick-links">
                    <ul class="all-links">
                        <li><a href="https://themezone.live" title="Get all premier themes">Codepen Themes</a></li>
                        <li><a href="https://blog.codepen.live" title="Get all premier themes">Codepen Blog</a></li>
                        <li><a href="https://cdn.codepen.live" title="Get all premier themes">Codepen CDN</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}